name: CI

on:
  push:
    branches: [ * ]

  workflow_dispatch:

env:
  apiKey: ${{ secrets.APIKEY }}
  authDomain: ${{ secrets.AUTHDOMAIN }}
  projectId: ${{ secrets.PROJECTID }}

jobs:

  build:
  
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0

      - name: Install Packages
        run: npm install 
        
      - name: Run Tests
        run: npm run test 


